openapi: 3.0.0
info:
  title: Purchase and Authentication API
  description: API for managing purchases and authentication
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

paths:
  /auth/login:
    post:
      summary: Authenticate user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Unauthorized

  /purchase/file:
    post:
      summary: Upload purchase file
      tags:
        - PurchaseFile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: File uploaded successfully
        '401':
          description: Unauthorized
    get:
      summary: Get purchases files summarized
      tags:
        - PurchaseFile
      security:
        - BearerAuth: []
      parameters:
        - name: fileName
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseFileResponse'
        '401':
          description: Unauthorized

  /purchase:
    get:
      summary: Get purchases records details by file
      tags:
        - Purchase
      security:
        - BearerAuth: []
      parameters:
        - name: fileName
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseResponse'
        '401':
          description: Unauthorized

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        jwt:
          type: string

    PurchaseResponse:
      type: object
      properties:
        purchaserName:
          type: string
        itemDescription:
          type: string
        itemPrice:
          type: number
          format: decimal
        purchaseCount:
          type: integer
        merchantAddress:
          type: string
        merchantName:
          type: string
        inclusionDate:
          type: string
          format: date-time

    PurchaseFileResponse:
      type: object
      properties:
        fileName:
          type: string
        inclusionDate:
          type: string
          format: date-time
        gross:
          type: number
          format: decimal
