openapi: 3.0.0
info:
  title: Purchase and Authentication API
  description: API for managing purchases and authentication
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

paths:
  /auth/login:
    post:
      summary: Authenticate user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Unauthorized

  /purchase/upload:
    post:
      summary: Upload purchase file
      tags:
        - Purchase
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: string
                format: uuid

  /purchase/{correlationId}:
    get:
      summary: Get purchases file by correlation ID
      tags:
        - Purchase
      parameters:
        - name: correlationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseResponse'

  /purchase/uploaded-files:
    get:
      summary: Get all uploaded files
      tags:
        - Purchase
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseFilesResponse'

components:
  schemas:
    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string

    PurchaseResponse:
      type: object
      properties:
        id:
          type: integer
        cpf:
          type: string
        private:
          type: boolean
        incompleto:
          type: boolean
        dataUltimaCompra:
          type: string
          format: date
        ticketMedio:
          type: number
        ticketUltimaCompra:
          type: number
        lojaMaisFrequente:
          type: string
        lojaUltimaCompra:
          type: string

    PurchaseFilesResponse:
      type: object
      properties:
        correlationId:
          type: string
          format: uuid
        fileName:
          type: string
        uploadDate:
          type: string
          format: date-time
